---
version: '3'

services:
  # frontend:
  #   image: node
  #   volumes:
  #     - ./frontend:/var/www/app

  backend:
    image: amazoncorretto:18-alpine3.15
    depends_on:
      - db
    working_dir: /var/www/app
    volumes:
      - ./api:/var/www/app
      - ./cache:/root/.m2
    ports:
      - 8080:8080
    env_file:
      - .env.dev
    command: ./mvnw spring-boot:run

  db:
    image: postgres:14-alpine3.16
    restart: always
    env_file:
      - .env.dev